import "./globals.css";
import { NextAuthProvider } from "@/components/providers";
import { NavBar } from "@/components/layout/navbar";
import { SiteFooter } from "@/components/layout/site-footer";
import { ThemeProvider } from "@/components/theme-provider"

import { notFound } from "next/navigation";
import { getCurrentUser } from "@/lib/session";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();

  if (!user) {
    return notFound();
  }

  return (
    <html lang="en">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <NavBar user={user} scroll={false} />
        <NextAuthProvider>{children}</NextAuthProvider>
        <SiteFooter className="border-t" />
      </ThemeProvider>
      </body>
    </html>
  );
}
